In [1]:
import pandas as pd
import numpy as np

In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\boardroom\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\boardroom\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\boardroom\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\boardroom\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\boardroom\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\boardroom\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
!pip install numpy

Requirement already satisfied: numpy in c:\users\boardroom\anaconda3\lib\site-packages (2.3.5)

In [1]:
import pandas as pd
import numpy as np

In [12]:
price_data = pd.read_csv("nigerian_market_prices_assignment.csv")

In [13]:
print("read data", price_data)

read data     market_id     market_name  state   product    price          unit  \
0      MKT001   Bodija Market    Oyo     Beans   ₦5,770            Kg
1      MKT003   Ogbete Market  Enugu       Yam   ₦2,534        basket
2      MKT001   Bodija Market    Oyo       Yam      NaN          50kg
3      MKT004     Wuse Market  Abuja  Tomatoes      NaN  Paint Rubber
4      MKT003   Ogbete Market  Enugu      Gari    -2616            kg
..        ...             ...    ...       ...      ...           ...
995    MKT002         Mile 12  Lagos  Tomatoes   ₦3,726          50kg
996    MKT001   Bodija Market    Oyo      Gari   ₦1,091            Kg
997    MKT002         Mile 12  Lagos      Rice  ₦46,603        basket
998    MKT002         Mile 12  Lagos      Rice  ₦49,114  Paint Rubber
999    MKT005  Ariaria Market   Abia       Yam   ₦3,415        basket

           date  trader_name
0    01-02-2024  mama nkechi
1    07/02/2024        bello
2    22/02/2024  alhaji musa
3    29-01-2024  mama nkechi
4    2024/01/31       sadiya
..          ...          ...
995  15/02/2024       SADIYA
996  10-03-2024  alhaji musa
997  29/02/2024  alhaji musa
998  2024-02-01       sadiya
999  2024-02-08        bello

[1000 rows x 8 columns]

In [15]:
#lets me showcase the data
price_data.head()

,market_id,market_name,state,product,price,unit,date,trader_name
0,MKT001,Bodija Market,Oyo,Beans,"₦5,770",Kg,01-02-2024,mama nkechi
1,MKT003,Ogbete Market,Enugu,Yam,"₦2,534",basket,07/02/2024,bello
2,MKT001,Bodija Market,Oyo,Yam,NaN,50kg,22/02/2024,alhaji musa
3,MKT004,Wuse Market,Abuja,Tomatoes,NaN,Paint Rubber,29-01-2024,mama nkechi
4,MKT003,Ogbete Market,Enugu,Gari,-2616,kg,2024/01/31,sadiya

In [17]:
price_data.isnull().sum()

market_id       0
market_name     0
state           0
product         0
price          75
unit            0
date            0
trader_name     0
dtype: int64

In [20]:
## i want to understand the Datatype, misssig values and structure

price_data.info()
price_data.describe(include="all")
price_data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   market_id    1000 non-null   object
 1   market_name  1000 non-null   object
 2   state        1000 non-null   object
 3   product      1000 non-null   object
 4   price        925 non-null    object
 5   unit         1000 non-null   object
 6   date         1000 non-null   object
 7   trader_name  1000 non-null   object
dtypes: object(8)
memory usage: 62.6+ KB

market_id       0
market_name     0
state           0
product         0
price          75
unit            0
date            0
trader_name     0
dtype: int64

In [37]:
## handling missing values:
#lets first replace the price value that are showing NaN with Zeros

replaced = price_data.fillna(0)

In [38]:
replaced.head()

,market_id,market_name,state,product,price,unit,date,trader_name
0,MKT001,Bodija Market,Oyo,Beans,"₦5,770",Kg,01-02-2024,mama nkechi
1,MKT003,Ogbete Market,Enugu,Yam,"₦2,534",basket,07/02/2024,bello
2,MKT001,Bodija Market,Oyo,Yam,0,50kg,22/02/2024,alhaji musa
3,MKT004,Wuse Market,Abuja,Tomatoes,0,Paint Rubber,29-01-2024,mama nkechi
4,MKT003,Ogbete Market,Enugu,Gari,-2616,kg,2024/01/31,sadiya

# still handling missing value::: 

price_data["quantity"] = price_data["quantity"].fillna(price_data["quantity"].median())
price_data["unit_price"] = price_data["unit_price"].fillna(price_data["unit_price"].median())
price_data["total_amount"] = price_data["total_amount"].fillna(price_data["total_amount"].median())

price_data.head()